### ISSUE TITLE
Empty Space

### ISSUE THREAD

**Issue by kmlhsn** [tony-nguyen1/tony-nguyen1.github.io#4]
Make image responsive. there are empty space on right side on mobile view 
![image](https://user-images.githubusercontent.com/32615215/100124244-9b01cc80-2ea5-11eb-964a-e41582d457c1.png)

**Comment by tony-nguyen1** [comment]
Done
![image](https://user-images.githubusercontent.com/47113757/100158696-e2d82200-2eac-11eb-85b3-1cff0351175a.png)
