### ISSUE TITLE
Boy and girl image looks good on top of the "Histoire"

### ISSUE THREAD

**Issue by kmlhsn** [tony-nguyen1/tony-nguyen1.github.io#5]
Add "Boy and girl" image on the top of the "Histoire" on media queries/mobile view. I think it looks good
![image](https://user-images.githubusercontent.com/32615215/100124958-74906100-2ea6-11eb-9447-6163523f60b8.png)
![image](https://user-images.githubusercontent.com/32615215/100125256-c3d69180-2ea6-11eb-93fd-3a576b2a62f1.png)

**Comment by tony-nguyen1** [comment]
![image](https://user-images.githubusercontent.com/47113757/100158458-7d843100-2eac-11eb-8599-24036e90d2f4.png)

I decided to put them at the bottom.
Thx for the QA & test.
